CREATE TABLE `Building1` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`RemoteID` INT NOT NULL DEFAULT '0',
	`Name` VARCHAR(100) NOT NULL,
	`CustomName` VARCHAR(100) NULL DEFAULT NULL,
	`Value` FLOAT NOT NULL,
	`Room` INT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8mb4_general_ci'
;
